import urllib.request
import json
import os
import sys
import ssl
import streamlit as st


st.image("phi3.jpeg", width=500)
st.title('📖Welcome to your AI Assistant!🌐')

st.sidebar.title("📖Phi-3bot!🌐")
st.sidebar.caption("Made by an [Valentina Alto](https://www.linkedin.com/in/valentina-alto-6a0590148/)")
st.sidebar.info("""
Note: Be aware that the content provided by this application is generated by AI. While we strive to provide accurate and up-to-date information, there may be instances where the AI-generated content might be incorrect, outdated, or incomplete. 
We recommend users to use this information as a guide and to perform personal due diligence to verify the accuracy of the information provided. We are not responsible for any decisions made based on the information provided by this application.
"""
)

url = "your-flow-url"
api_key = "your-api-key"

def calling_pf(query):
    data = {"question": query}

    body = str.encode(json.dumps(data))
    headers = {'Content-Type':'application/json', 'Authorization':('Bearer '+ api_key), 'azureml-model-deployment': 'vaalt-sweden-hfgai-1' }

    req = urllib.request.Request(url, body, headers)

    try:
        response = urllib.request.urlopen(req)
        result = response.read()
        answer = json.loads(result.decode("utf-8").strip())['output']
        return answer
    except urllib.error.HTTPError as error:
        print("The request failed with status code: " + str(error.code))

        # Print the headers - they include the requert ID and the timestamp, which are useful for debugging the failure
        print(error.info())
        print(error.read().decode("utf8", 'ignore'))

query = st.text_area("Ask me anything")

if query:
    output = calling_pf(query)
    st.write(output)
